services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: soko_user
      POSTGRES_PASSWORD: soko_pass
      POSTGRES_DB: soko_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.dev
      DATABASE_URL: postgres://soko_user:soko_pass@db:5432/soko_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    env_file:
      - .env.dev

volumes:
  postgres_data:
